 till†ts inte
 saknas
konstant
 inte
uttryck
identifierare
fil
 data
Heltal
Fil
F”rbjude
 eller
Odefinierad
 ”verensst„mmer
 reell
Str„ng
Textfil
 utanf”r till†tet omr†de
 variabel
Minnet fullt
 f”rv„ntas
typ
Felaktig
 pekare
01';'
02':'
03','
04'('
05')'
06'='
07':='
08'(. ['
09'.) ]'
10'.'
11'..'
12BEGIN
13DO
14END
15OF
16PROCEDURE FUNCTION
17THEN
18TO DOWNTO
20Booleskt 
21
22
23
24
25
26
27
28Pekar
29Post
30Enkel
31Enkelt 
32
33
34
35
36Datas
37 utan
40 LABEL
41Ok„nd  syntaxfel
42 i f”reg†ende definitioner
43Dubbeltydig  LABEL
44Typer
45
46ens och CASE-v„ljarens
47Operand(er) med operator
48 resultat
49 l„ngd
50ens l„ngd en
51 grund i delintervall
52L„gre gr„nsen > ”vre gr„nsen
53Reserverat ord
54n tilldelning
55 l„ngre „n raden
56Fel i heltals
57Fel i 
58t tecken i 
60er
61er och h„r
62Strukturerade variabler h„r
63er h„r
64er och er utan
65Ler utan  h„r
66I/O
67er m†ste vara-parametrar
68Elementen i en f†r  vara er
69 ordning p† f„lt
70SM„ngdens element
71t GOTO
72LABEL ligger i aktuellt block
73 FORWARD procedur(er)
74INLINE fel
75n anv„ndning av ABSOLUTE
76Overlayer f†r FORWARD-refereras
77Overlayer i direkt mod
90en
91Ov„ntat slut p† k„llfil
92Kan skapa overlayer
93t kompileringsdirektiv
96N„stlade includeer
97F”r m†nga n„stlade WITH
98
99 vid kompilering